/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import biblioteca.Conexion;
import java.sql.Statement;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;

/**
 *
 * @author HP
 */
public class FrmEditorial extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditorial
     */
    Conexion cn;
    public FrmEditorial() {
        initComponents();
        cn=new Conexion();
        cn.conectar();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(0);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        txt_idEditorial = new javax.swing.JTextField();
        btn_buscarEdit = new javax.swing.JButton();
        btn_salirEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Contacto = new javax.swing.JLabel();
        txt_nombreEdit = new javax.swing.JTextField();
        txt_direccionEdit = new javax.swing.JTextField();
        txt_contactoEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(673, 449));

        Titulo.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(13, 59, 102));
        Titulo.setText("EDITORIAL");

        id.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(74, 74, 74));
        id.setText("ID");

        txt_idEditorial.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_idEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idEditorialActionPerformed(evt);
            }
        });

        btn_buscarEdit.setBackground(new java.awt.Color(39, 174, 96));
        btn_buscarEdit.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btn_buscarEdit.setForeground(new java.awt.Color(0, 0, 0));
        btn_buscarEdit.setText("BUSCAR");
        btn_buscarEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_buscarEdit.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_buscarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarEditActionPerformed(evt);
            }
        });

        btn_salirEdit.setBackground(new java.awt.Color(255, 59, 59));
        btn_salirEdit.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btn_salirEdit.setForeground(new java.awt.Color(0, 0, 0));
        btn_salirEdit.setText("SALIR");
        btn_salirEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_salirEdit.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_salirEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirEditActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Datos de editorial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 12))); // NOI18N

        Nombre.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(74, 74, 74));
        Nombre.setText("Nombre");

        Direccion.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(74, 74, 74));
        Direccion.setText("Dirección");

        Contacto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Contacto.setForeground(new java.awt.Color(74, 74, 74));
        Contacto.setText("Contacto");

        txt_nombreEdit.setEditable(false);
        txt_nombreEdit.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_nombreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEditActionPerformed(evt);
            }
        });

        txt_direccionEdit.setEditable(false);
        txt_direccionEdit.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_direccionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionEditActionPerformed(evt);
            }
        });

        txt_contactoEdit.setEditable(false);
        txt_contactoEdit.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_contactoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactoEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Direccion)
                    .addComponent(Nombre)
                    .addComponent(Contacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_direccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contactoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion)
                    .addComponent(txt_direccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contactoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contacto))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_buscarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_idEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo))
                        .addGap(281, 281, 281))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idEditorialActionPerformed

    private void txt_nombreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEditActionPerformed

    private void txt_direccionEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionEditActionPerformed

    private void txt_contactoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactoEditActionPerformed

    private void btn_salirEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirEditActionPerformed
    FrmMenuLibro verpanel= new FrmMenuLibro();
    verpanel.setVisible(true);
    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirEditActionPerformed

    private void btn_buscarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarEditActionPerformed
    try {
            // TODO add your handling code here:
            String id_editorial = this.txt_idEditorial.getText();
            String consultar = "SELECT *FROM editorial WHERE id_editorial = '"+id_editorial+"'";
            Statement st = cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(consultar);
            if(rs.next()){
                this.txt_nombreEdit.setText(rs.getString("nombre"));
                this.txt_direccionEdit.setText(rs.getString("direccion"));
                this.txt_contactoEdit.setText(rs.getString("contacto"));
          
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmEditorial.class.getName()).log(Level.SEVERE, null, ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contacto;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn_buscarEdit;
    private javax.swing.JButton btn_salirEdit;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_contactoEdit;
    private javax.swing.JTextField txt_direccionEdit;
    private javax.swing.JTextField txt_idEditorial;
    private javax.swing.JTextField txt_nombreEdit;
    // End of variables declaration//GEN-END:variables
}
