/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import biblioteca.Conexion;
import java.sql.Statement;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;

/**
 *
 * @author HP
 */
public class FrmLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrmLibro
     */
    Conexion cn;
    public FrmLibro() {
        initComponents();
        cn=new Conexion();
        cn.conectar();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(0);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        txt_codLibro = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Panel_datos = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        Autor = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        Categoria = new javax.swing.JLabel();
        txt_idCategoria = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        txt_numEjemplares = new javax.swing.JTextField();
        Editorial = new javax.swing.JLabel();
        txt_idEditorial = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        Publicacion = new javax.swing.JLabel();
        txtPublicacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(606, 550));

        Titulo.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(13, 59, 102));
        Titulo.setText("LIBRO");

        Codigo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Codigo.setForeground(new java.awt.Color(74, 74, 74));
        Codigo.setText("Código");

        txt_codLibro.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_codLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codLibroActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 59, 59));
        Salir.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("SALIR");
        Salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Salir.setPreferredSize(new java.awt.Dimension(24, 24));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(39, 174, 96));
        Buscar.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 0));
        Buscar.setText("BUSCAR");
        Buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Buscar.setPreferredSize(new java.awt.Dimension(24, 24));
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Panel_datos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Datos del libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 12))); // NOI18N

        Nombre.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(74, 74, 74));
        Nombre.setText("Título");

        txt_titulo.setEditable(false);
        txt_titulo.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        Autor.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Autor.setForeground(new java.awt.Color(74, 74, 74));
        Autor.setText("Autor");

        txt_autor.setEditable(false);
        txt_autor.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autorActionPerformed(evt);
            }
        });

        Categoria.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Categoria.setForeground(new java.awt.Color(74, 74, 74));
        Categoria.setText("Categoría");

        txt_idCategoria.setEditable(false);
        txt_idCategoria.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_idCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCategoriaActionPerformed(evt);
            }
        });

        Cantidad.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(74, 74, 74));
        Cantidad.setText("Cantidad");

        txt_numEjemplares.setEditable(false);
        txt_numEjemplares.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_numEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numEjemplaresActionPerformed(evt);
            }
        });

        Editorial.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Editorial.setForeground(new java.awt.Color(74, 74, 74));
        Editorial.setText("Editorial");

        txt_idEditorial.setEditable(false);
        txt_idEditorial.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_idEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idEditorialActionPerformed(evt);
            }
        });

        Estado.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Estado.setForeground(new java.awt.Color(74, 74, 74));
        Estado.setText("Estado");

        txt_estado.setEditable(false);
        txt_estado.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });

        Publicacion.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Publicacion.setForeground(new java.awt.Color(74, 74, 74));
        Publicacion.setText("Publicación");

        txtPublicacion.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        javax.swing.GroupLayout Panel_datosLayout = new javax.swing.GroupLayout(Panel_datos);
        Panel_datos.setLayout(Panel_datosLayout);
        Panel_datosLayout.setHorizontalGroup(
            Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_datosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cantidad)
                            .addComponent(Editorial)
                            .addComponent(Estado)
                            .addComponent(Publicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_numEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_datosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Autor)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        Panel_datosLayout.setVerticalGroup(
            Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_datosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Autor))
                .addGap(9, 9, 9)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad)
                    .addComponent(txt_numEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estado)
                    .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Publicacion)
                    .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_codLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo))
                .addGap(18, 18, 18)
                .addComponent(Panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codLibroActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    private void txt_idCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCategoriaActionPerformed

    private void txt_numEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numEjemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numEjemplaresActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void txt_idEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idEditorialActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    FrmMenuLibro Frm= new FrmMenuLibro();
    Frm.setVisible(true);
    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
    try {
            // TODO add your handling code here:
            String cod_libro = this.txt_codLibro.getText();
            String consultar = "SELECT a.Titulo,a.Autor,b.Nom_categoria,a.Num_de_ejemplares,a.Estado,c.Nombre,a.Fecha_publicacion FROM libro AS a INNER JOIN categoria AS b ON  a.ID_Categoria=b.ID_categoria\n" +
            "INNER JOIN editorial AS c ON a.ID_editorial=c.ID_Editorial\n" +
            "WHERE a.Cod_libro= '"+cod_libro+"'";
            Statement st = cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(consultar);
            if(rs.next()){
                this.txt_titulo.setText(rs.getString("a.Titulo"));
                this.txt_autor.setText(rs.getString("a.Autor"));
                this.txt_idCategoria.setText(rs.getString("b.Nom_categoria"));
                this.txt_numEjemplares.setText(rs.getString("a.Num_de_ejemplares"));
                this.txt_estado.setText(rs.getString("a.Estado"));
                this.txt_idEditorial.setText(rs.getString("c.Nombre"));
                this.txtPublicacion.setText(rs.getString("a.Fecha_publicacion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmLibro.class.getName()).log(Level.SEVERE, null, ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Editorial;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Panel_datos;
    private javax.swing.JLabel Publicacion;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField txtPublicacion;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_codLibro;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_idCategoria;
    private javax.swing.JTextField txt_idEditorial;
    private javax.swing.JTextField txt_numEjemplares;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
