/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import biblioteca.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class FrmMulta extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu; 
    /**
     * Creates new form panelbiblioteca
     */
    Conexion cn;
    DefaultTableModel modelo;
    public FrmMulta() {
        initComponents();
        cn=new Conexion();
        cn.conectar();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(0);
        this.setResizable(false);
        modelo = (DefaultTableModel) Tabla.getModel();
        ListarMultas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        PanelSelection = new javax.swing.JPanel();
        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Añadir = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        PanelOption = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        Motivo = new javax.swing.JLabel();
        Monto = new javax.swing.JLabel();
        txt_DNI = new javax.swing.JTextField();
        cbMotivo = new javax.swing.JComboBox<>();
        txt_Monto = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(933, 759));

        Titulo.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(13, 59, 102));
        Titulo.setText("MULTA");

        Tabla.setBackground(new java.awt.Color(153, 153, 255));
        Tabla.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Motivo", "Monto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setSelectionBackground(new java.awt.Color(102, 153, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        Scroll.setViewportView(Tabla);

        PanelSelection.setBackground(new java.awt.Color(255, 255, 255));
        PanelSelection.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Opciones ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 12))); // NOI18N

        Editar.setBackground(new java.awt.Color(204, 0, 255));
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-editar.png"))); // NOI18N
        Editar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(255, 102, 102));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar.png"))); // NOI18N
        Eliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Añadir.setBackground(new java.awt.Color(153, 255, 102));
        Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        Añadir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Nuevo.setBackground(new java.awt.Color(255, 255, 102));
        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-de-nuevo-documento.png"))); // NOI18N
        Nuevo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(0, 204, 153));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/REGRE.png"))); // NOI18N
        Salir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSelectionLayout = new javax.swing.GroupLayout(PanelSelection);
        PanelSelection.setLayout(PanelSelectionLayout);
        PanelSelectionLayout.setHorizontalGroup(
            PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectionLayout.createSequentialGroup()
                .addGroup(PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelSelectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSelectionLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        PanelSelectionLayout.setVerticalGroup(
            PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        PanelOption.setBackground(new java.awt.Color(255, 255, 255));
        PanelOption.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Ingresar datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 12))); // NOI18N

        DNI.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        DNI.setForeground(new java.awt.Color(74, 74, 74));
        DNI.setText("DNI");

        Motivo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Motivo.setForeground(new java.awt.Color(74, 74, 74));
        Motivo.setText("Motivo");

        Monto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Monto.setForeground(new java.awt.Color(74, 74, 74));
        Monto.setText("Monto");

        txt_DNI.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        txt_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DNIActionPerformed(evt);
            }
        });

        cbMotivo.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        cbMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Devolución tardía", "Daño al libro", "Pérdida del libro" }));
        cbMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMotivoActionPerformed(evt);
            }
        });

        txt_Monto.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N

        Estado.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Estado.setForeground(new java.awt.Color(74, 74, 74));
        Estado.setText("Estado");

        cbEstado.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagada", " " }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOptionLayout = new javax.swing.GroupLayout(PanelOption);
        PanelOption.setLayout(PanelOptionLayout);
        PanelOptionLayout.setHorizontalGroup(
            PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOptionLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelOptionLayout.createSequentialGroup()
                        .addComponent(Estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOptionLayout.createSequentialGroup()
                        .addComponent(Monto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOptionLayout.createSequentialGroup()
                        .addComponent(Motivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOptionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        PanelOptionLayout.setVerticalGroup(
            PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(PanelOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(PanelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(Titulo)))
                .addGap(99, 99, 99))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 933, 759));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        int row = Tabla.getSelectedRow();
        String ID_Multa = (String) Tabla.getValueAt(row, 0);
        String DNI = this.txt_DNI.getText();
        String Motivo = this.cbMotivo.getSelectedItem().toString();
        String Monto = this.txt_Monto.getText();
        String Estado = this.cbEstado.getSelectedItem().toString();
        String editar = "UPDATE multa SET DNI='" + DNI + "', Motivo='" + Motivo + "', Monto='" + Monto + "', Estado='" + Estado + "' WHERE ID_Multa=" + ID_Multa;
        try{
        Statement st = cn.conectar().createStatement();
        st.executeUpdate(editar);
        }catch(SQLException ex){
            Logger.getLogger(FrmMulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Multa modificada correctamente.");
        ListarMultas();
        Limpiar();
    }//GEN-LAST:event_EditarActionPerformed

    public void Limpiar()
    {
       this.txt_DNI.setText("");
       this.txt_Monto.setText("");
       this.cbMotivo.setSelectedIndex(-1);
       this.cbEstado.setSelectedIndex(-1); 
    }
    public void ListarMultas()
    {
    try {
        limpiarTabla();
        String listar = "SELECT * FROM multa ORDER BY ID_Multa";
        Statement st = cn.conectar().createStatement();
        ResultSet rs = st.executeQuery(listar);
        modelo = (DefaultTableModel) this.Tabla.getModel();
        
        while (rs.next()) {
            Object[] persona = new Object[5]; 
            persona[0] = rs.getString("ID_Multa");
            persona[1] = rs.getString("DNI");
            persona[2] = rs.getString("Motivo");
            persona[3] = rs.getString("Monto");
            persona[4] = rs.getString("Estado");
            modelo.addRow(persona);
        }
        Tabla.setModel(modelo);
    } catch (SQLException e) {
        Logger.getLogger(FrmMulta.class.getName()).log(Level.SEVERE, null, e); // Manejar la excepción
    }
    }
    void limpiarTabla(){
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
     try {
        String DNI = this.txt_DNI.getText();
        String Motivo = this.cbMotivo.getSelectedItem().toString();
        String Monto = this.txt_Monto.getText();
        String Estado = this.cbEstado.getSelectedItem().toString();
        String insertar = "INSERT INTO multa (DNI,Motivo,Monto,Estado) VALUES('" + DNI + "','" + Motivo + "','" + Monto + "','" + Estado + "')";
        Statement st = cn.conectar().createStatement();
        int rs = st.executeUpdate(insertar);
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Se agregó la multa correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo agregar la multa correctamente.");
            }
        ListarMultas();
        Limpiar();
    } catch (SQLException ex) {
        Logger.getLogger(FrmPrestamo.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_AñadirActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        FrmMenuGestion verpanel= new FrmMenuGestion();
        verpanel.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
    Limpiar();
    }//GEN-LAST:event_NuevoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    int row = Tabla.getSelectedRow();
    String ID_Multa = (String) Tabla.getValueAt(row, 0);
    String eliminar = "DELETE FROM multa WHERE ID_Multa = '"+ ID_Multa +"'";        
    int fila = Tabla.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,"Multa no Seleccionada");
        } else{
                try {
                Statement st = cn.conectar().createStatement();
                st.executeUpdate(eliminar);
                JOptionPane.showMessageDialog(null, "Multa eliminada");
                Limpiar();
                }catch(Exception e){
                }  
        }
    ListarMultas();
    Limpiar();
    }//GEN-LAST:event_EliminarActionPerformed

    private void cbMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMotivoActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int row = Tabla.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "No se seleccionó");
        }else{
            String DNI = (String) Tabla.getValueAt(row, 1);
            String Motivo = (String) Tabla.getValueAt(row, 2);
            String Monto = (String) Tabla.getValueAt(row, 3);
            String Estado = (String) Tabla.getValueAt(row, 4);
            txt_Monto.setText(Monto);
            txt_DNI.setText(DNI);
            cbMotivo.setSelectedItem(Motivo);
            cbEstado.setSelectedItem(Estado);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void txt_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DNIActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JLabel DNI;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Monto;
    private javax.swing.JLabel Motivo;
    private javax.swing.JButton Nuevo;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PanelOption;
    private javax.swing.JPanel PanelSelection;
    private javax.swing.JButton Salir;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbMotivo;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_Monto;
    // End of variables declaration//GEN-END:variables
}
